Repository kookmin-sw/capstone-2024-04, pull requests merged in 2024-04, with the labels that each got.

#57 `HomePage` 기본 UI 구현 및 요소 배치
  src/client/src/App.tsx
  src/client/src/assets/icons/InfoCircle.svg
  src/client/src/assets/icons/account-blacksub.svg
  src/client/src/assets/icons/account-whitesub.svg
  src/client/src/assets/icons/chart-timeline-blacksub.svg
  src/client/src/assets/icons/chart-timeline-whitesub.svg
  src/client/src/assets/icons/clipboard-text-clock-blacksub.svg
  src/client/src/assets/icons/clipboard-text-clock-whitesub.svg
  src/client/src/assets/icons/cog-blacksub.svg
  src/client/src/assets/icons/cog-whitesub.svg
  src/client/src/assets/icons/file-compare-blacksub.svg
  src/client/src/assets/icons/file-compare-whitesub.svg
  src/client/src/assets/icons/list-box-blacksub.svg
  src/client/src/assets/icons/list-box-whitesub.svg
  src/client/src/assets/icons/upload-blacksub.svg
  src/client/src/assets/icons/upload-whitesub.svg
  src/client/src/assets/icons/view-dashboard-blacksub.svg
  src/client/src/assets/icons/view-dashboard-whitesub.svg
  src/client/src/assets/images/LogoBlack.svg
  src/client/src/assets/images/LogoMain.svg
  src/client/src/assets/images/LogoWhite.svg
  src/client/src/components/menu_button.tsx
  src/client/src/pages/home/home.tsx
  src/client/src/pages/main/main.tsx
  src/client/tailwind.config.js
Labels: 새로운 기능 및 요청, 클라이언트

#61 API 요청 관련 초기 설정 및 회원가입, 로그인 연결
  package.json
  src/client/package.json
  src/client/src/api/apply.ts
  src/client/src/api/auth.ts
  src/client/src/api/location.ts
  src/client/src/api/media.ts
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/yarn.lock
  yarn.lock
Labels: 버그 및 오류, 새로운 기능 및 요청, 클라이언트

#62 5주차 `client/develop` to `master`
  package.json
  src/client/package.json
  src/client/src/App.tsx
  src/client/src/api/apply.ts
  src/client/src/api/auth.ts
  src/client/src/api/location.ts
  src/client/src/api/media.ts
  src/client/src/assets/icons/InfoCircle.svg
  src/client/src/assets/icons/account-blacksub.svg
  src/client/src/assets/icons/account-whitesub.svg
  src/client/src/assets/icons/chart-timeline-blacksub.svg
  src/client/src/assets/icons/chart-timeline-whitesub.svg
  src/client/src/assets/icons/clipboard-text-clock-blacksub.svg
  src/client/src/assets/icons/clipboard-text-clock-whitesub.svg
  src/client/src/assets/icons/cog-blacksub.svg
  src/client/src/assets/icons/cog-whitesub.svg
  src/client/src/assets/icons/file-compare-blacksub.svg
  src/client/src/assets/icons/file-compare-whitesub.svg
  src/client/src/assets/icons/list-box-blacksub.svg
  src/client/src/assets/icons/list-box-whitesub.svg
  src/client/src/assets/icons/upload-blacksub.svg
  src/client/src/assets/icons/upload-whitesub.svg
  src/client/src/assets/icons/view-dashboard-blacksub.svg
  src/client/src/assets/icons/view-dashboard-whitesub.svg
  src/client/src/assets/images/LogoBlack.svg
  src/client/src/assets/images/LogoMain.svg
  src/client/src/assets/images/LogoWhite.svg
  src/client/src/components/menu_button.tsx
  src/client/src/pages/home/home.tsx
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/tailwind.config.js
  src/client/yarn.lock
  yarn.lock
Labels: 버그 및 오류, 새로운 기능 및 요청, 클라이언트

#64 모델 5주차 PR
  src/model/demo/main.py
  src/model/demo/pages/1_Detect_Demo.py
  src/model/demo/pages/2_LOOK_Demo.py
  src/model/fastapi/README.md
  src/model/fastapi/kafkaProducer.py
  src/model/lab/240404-01-Looking-Demo.ipynb
  src/model/lab/240404-01-ptgaze.ipynb
  src/model/lab/240404-02-Looking-Demo.ipynb
  src/model/pipeline/__init__.py
  src/model/pipeline/gaze.py
  src/model/pipeline/par.py
  src/model/pipeline/pipeline.py
  src/model/pipeline/tracker.py
Labels: 모델

#75 모델 6주차 PR
  src/model/pipeline/look.py
  src/model/pipeline/pipeline.py
  src/model/pipeline/tracker.py
Labels: 모델

#76 Chore: Git hooks 추가(lint, commit lint)
  .gitmessage.txt
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: 새로운 기능 및 요청, 클라이언트, 서버, 모델

#81 Feat: 광고 등록하기 화면 UI 구현 완료
  src/client/index.html
  src/client/public/logo.svg
  src/client/public/vite.svg
  src/client/src/assets/icons/Inbox.svg
  src/client/src/assets/icons/Upload.svg
  src/client/src/components/text.tsx
  src/client/src/pages/home/home.tsx
  src/client/src/pages/home/post-media/post_media.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/tailwind.config.js
Labels: 새로운 기능 및 요청, 클라이언트

#82 Feat: cookie를 통한 `refreshToken`, `accessToken` 관리 및 자동 로그인(로그인 유지) 기능 구현
  src/client/package.json
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/yarn.lock
Labels: 새로운 기능 및 요청, 클라이언트

#85 Feat: 비밀번호 찾기 UI 구현, `MainPage` 내부 스크린 전환 로직 변경
  src/client/src/pages/main/find_password.tsx
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
Labels: 새로운 기능 및 요청, 클라이언트

#87 Feat: 설정 페이지 구현(비밀번호 변경 UI, 로그아웃 기능 구현)
  src/client/src/pages/home/home.tsx
  src/client/src/pages/home/setting/setting.tsx
Labels: 새로운 기능 및 요청, 클라이언트

#88 Feat: 광고 비교 UI 구현
  src/client/src/assets/icons/Vector.svg
  src/client/src/assets/icons/account-multiple.svg
  src/client/src/assets/icons/bullseye-arrow.svg
  src/client/src/assets/icons/exclamation-thick.svg
  src/client/src/assets/icons/eye-outline.svg
  src/client/src/assets/icons/face-man.svg
  src/client/src/assets/icons/face-woman.svg
  src/client/src/assets/icons/gender.svg
  src/client/src/assets/icons/walk.svg
  src/client/src/pages/home/compare-media/compare_media.tsx
  src/client/src/pages/home/home.tsx
  src/client/src/pages/home/post-media/post_media.tsx
Labels: 새로운 기능 및 요청, 클라이언트

#94 Feat: API 모듈화 추가 작업 및 권한 관련 설정 추가(라우팅, Axios 요청 관련)
  src/client/package.json
  src/client/src/App.tsx
  src/client/src/api/auth.ts
  src/client/src/api/location.ts
  src/client/src/api/private_api.ts
  src/client/src/api/public_api.ts
  src/client/src/components/media_card.tsx
  src/client/src/components/menu_button.tsx
  src/client/src/components/status_badge.tsx
  src/client/src/interfaces/interface.ts
  src/client/src/main.tsx
  src/client/src/pages/home/compare-media/compare_media.tsx
  src/client/src/pages/home/post-media/post_media.tsx
  src/client/src/pages/main/find_password.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/yarn.lock
Labels: 새로운 기능 및 요청, 클라이언트

#95 Client/develop
  src/client/index.html
  src/client/package.json
  src/client/public/logo.svg
  src/client/public/vite.svg
  src/client/src/App.tsx
  src/client/src/api/auth.ts
  src/client/src/api/location.ts
  src/client/src/api/private_api.ts
  src/client/src/api/public_api.ts
  src/client/src/assets/icons/Inbox.svg
  src/client/src/assets/icons/Upload.svg
  src/client/src/assets/icons/Vector.svg
  src/client/src/assets/icons/account-multiple.svg
  src/client/src/assets/icons/bullseye-arrow.svg
  src/client/src/assets/icons/exclamation-thick.svg
  src/client/src/assets/icons/eye-outline.svg
  src/client/src/assets/icons/face-man.svg
  src/client/src/assets/icons/face-woman.svg
  src/client/src/assets/icons/gender.svg
  src/client/src/assets/icons/walk.svg
  src/client/src/components/media_card.tsx
  src/client/src/components/menu_button.tsx
  src/client/src/components/status_badge.tsx
  src/client/src/components/text.tsx
  src/client/src/interfaces/interface.ts
  src/client/src/main.tsx
  src/client/src/pages/home/compare-media/compare_media.tsx
  src/client/src/pages/home/home.tsx
  src/client/src/pages/home/post-media/post_media.tsx
  src/client/src/pages/home/setting/setting.tsx
  src/client/src/pages/main/find_password.tsx
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/tailwind.config.js
  src/client/yarn.lock
Labels: 새로운 기능 및 요청, 클라이언트

#105 Feat: 대시보드 선택 전 UI 구현
  src/client/src/components/media_card.tsx
  src/client/src/interfaces/interface.ts
  src/client/src/main.tsx
  src/client/src/pages/home/dashboard/dashboard.tsx
  src/client/src/pages/home/dashboard/dashboard_detail.tsx
  src/client/src/pages/home/gridview-media/gridview_media.tsx
  src/client/src/pages/home/home.tsx
Labels: 새로운 기능 및 요청, 클라이언트
