Repository kookmin-sw/capstone-2024-04, pull requests merged in 2024-03, with the labels that each got.

#14 클라이언트 개발 환경 초기 세팅
  package-lock.json
  src/client/.eslintrc.cjs
  src/client/.gitignore
  src/client/README.md
  src/client/index.html
  src/client/package-lock.json
  src/client/package.json
  src/client/postcss.config.js
  src/client/public/vite.svg
  src/client/src/App.tsx
  src/client/src/assets/react.svg
  src/client/src/index.css
  src/client/src/main.tsx
  src/client/src/pages/main.tsx
  src/client/src/vite-env.d.ts
  src/client/tailwind.config.js
  src/client/tsconfig.json
  src/client/tsconfig.node.json
  src/client/vite.config.ts
  src/client/yarn.lock
Labels: 새로운 기능 및 요청, 클라이언트

#28 `README.md` 파일 수정(팀원 소개 추가, 불필요 내용 삭제)
  README.md
Labels: 문서 작업

#34 클라이언트 회원가입, 로그인 화면 UI 구현 및 반응형 디자인 적용
  src/client/index.html
  src/client/src/App.tsx
  src/client/src/assets/images/carousel_1.svg
  src/client/src/assets/images/logo.svg
  src/client/src/index.css
  src/client/src/pages/main.tsx
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/tailwind.config.js
Labels: 새로운 기능 및 요청, 클라이언트

#35 Client `develop` to `master`
  src/client/index.html
  src/client/src/App.tsx
  src/client/src/assets/images/carousel_1.svg
  src/client/src/assets/images/logo.svg
  src/client/src/index.css
  src/client/src/pages/main.tsx
  src/client/src/pages/main/main.tsx
  src/client/src/pages/main/sign_in.tsx
  src/client/src/pages/main/sign_up.tsx
  src/client/tailwind.config.js
Labels: 새로운 기능 및 요청, 클라이언트

#33 Model 3주차 PR
  src/model/.gitignore
  src/model/fastapi/main.py
  src/model/fastapi/mot.py
  src/model/fastapi/par.py
  src/model/lab/240320-01-BoT-SORT-demo.ipynb
  src/model/lab/240321-01-PAR-MarketDude.ipynb
  src/model/lab/README.md
Labels: 모델

#50 모델 4주차 PR
  src/model/lab/240320-01-BoT-SORT-demo.ipynb
  src/model/lab/240325-01-BoxMOT.ipynb
  src/model/lab/240326-01-HeadPose(6DRepNet).ipynb
Labels: 모델

#51 `README.md` 파일 업데이트 (~ 중간 발표)
  README.md
Labels: 문서 작업
